Append, Insert, Delete  Operations
np.append([array 1D, 2D array],axis=0 or 1)
axis =0 adding new rows
axis=1 adding new columns
[0,1,2] [[3,4,5],[6,7,8]]  append two array in row format
0 1 2
3 4 5
6 7 8

given array 0 0
            1 1
            2 2
np.insert([1],[[3],[4][5]],axis =1)  #add columns on index 1 in each row
 it will add new columns to add the numbers
 0 3 0
 1 4 1
 2 5 2

0 1 2
4 5 6
7 8 9
 np.delete(1,0)  index is 1 ,  0 means row
output =
0 1 2
7 8 9





In [18]:
import numpy as np
a=np.array([[1,23,3],[2,3,4],[2,3,4]])
#append method
np.append(a,[7,8,9])
print(np.append(a,[7,8,9]))
print(np.append(a,[[7,8,9]],axis=0))
print(np.append(a,[[7],[8],[9]],axis=1))

[ 1 23  3  2  3  4  2  3  4  7  8  9]
[[ 1 23  3]
 [ 2  3  4]
 [ 2  3  4]
 [ 7  8  9]]
[[ 1 23  3  7]
 [ 2  3  4  8]
 [ 2  3  4  9]]


In [19]:
a=np.array([[1,2],
            [3,4],
            [5,6]])
print(np.insert(a,3,[11,12]))
print(np.insert(a,2,[11,12],axis=0))
print(np.insert(a,1,[11,12,13],axis=1))

[ 1  2  3 11 12  4  5  6]
[[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]]
[[ 1 11  2]
 [ 3 12  4]
 [ 5 13  6]]


In [ ]:
a=np.array([[1,2,3,4],
           [3,4,5,6],
           [5,6,7,8]])
 #6 is a index
print(np.delete(a,6)) # delete index 6=5 and flatten the array
print(np.delete(a,2,axis=0))  # delete the row from index =2
print(np.delete(a,2,axis=1))  # delete the column on index 2

[1 2 3 4 3 4 6 5 6 7 8]
[[1 2 3 4]
 [3 4 5 6]]
[[1 2 4]
 [3 4 6]
 [5 6 8]]


In [ ]:
np.ndim(a)


2

Hstack vs Vstack
Hstack is used to join two arrays horizontally
Vstack is used to join two arrays vertically

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,b)
print(np.ndim(a),np.ndim(b))
result=np.hstack((a,b))
print(result,np.ndim(result))  # 1D array
vresult=np.vstack((a,b))
print(vresult,np.ndim(vresult)) # become 2D array

[1 2 3] [4 5 6]
1 1
[1 2 3 4 5 6] 1
[[1 2 3]
 [4 5 6]] 2


Numpy Concatenation

It is used for joining two or more arrays of the same shape along a specified axis
Axis=0, Adding new rows
Axis=1, Adding new columns

In [33]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[3],[9]])
arr4=np.array([[6,9]])
new =np.concatenate((arr1,arr2),axis=0)
print(new)
now=np.concatenate((arr1,arr2),axis=1)
print(now)


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
