<!-- Array Slicing
Slicing in python means taking elements from one given index to another given index
We pass slice instead of index like this: [start:end]
We can also define the step,like this:[start:end:step] -->
<!-- a
a[1,2]
a[1,:] whole 1 row
a[:,2] whole 2nd col
a[:,1:3] two columns 1,2
a[-2:,-2:] in negative case indexing starts from -1 , in this -1 or 1st column is not in -2 or second to all cols select also in cols
a[::2,1::2] rows is 0 and 2  cols are 1 and 3  -->


In [ ]:
import numpy as np
a1=np.array([1,32,24,56,7,89,9,9])  # slicing in 1 D array
print(a1[1:5]) #[start:end] from 1st index 32 to 5-1=4th index
print(a1[4:])  # ll from 4ht index to end
print(a1[:4])

[32 24 56  7]
[ 7 89  9  9]
[ 1 32 24 56]


In [ ]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])#2D array
print(a2[1,1:4])  #[row:column]
print(a2[0:2,2])
print(a2[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
a3=np.array([[[10,11,12],[13,14,15],[16,17,18]],
             [[19,20,21],[22,23,24],[25,26,27]],
             [[28,29,30],[31,32,33],[34,35,36]]]) # 3 D array Slicing
print(a3[:2,1:,:2])
print(a3.shape)

print(a3[:3,2,1])
print(a3[:3,:3,1])

[[[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]
(3, 3, 3)
[17 26 35]
[[11 14 17]
 [20 23 26]
 [29 32 35]]


View vs Copy
Copy is a new array, and the View is just a view of the original array.
Any changes made to the copy will not affect original array.
Any changes made to the view will affect the original array.

In [ ]:
arr=np.array([1,2,3,4,5])
# copy method
print(arr)
copy = arr.copy()
print(copy)
copy[0]=4
print(copy)
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]
[4 2 3 4 5]
[1 2 3 4 5]


In [ ]:
# View Method

import numpy as np
arra=np.array([1,2,4,5,6,7,8,9])
print(arra)
view=arra.view()
view[0]=43

print(view)
print(arra)  # change also

[1 2 4 5 6 7 8 9]
[43  2  4  5  6  7  8  9]
[43  2  4  5  6  7  8  9]
