In [2]:
import numpy as np

Numpy Array Dimension
1D, 2D, 3D Array

In [3]:
A=np.array(5)    #scalar array
print(A)
print(np.ndim(A))    # Dimension Method

5
0


In [ ]:
One=np.array([1,2,3,4,5])
Two=np.array([[1,2,3,4,5],[1,2,3,4,5]])
Three=np.array([[[1,2,3,4,4] ,[1,2,3,5,4]] ,[[1,2,3,4,4,4],[1,2,3,4,5]]])
print(One)
print(np.ndim(One))
print(Two)
print(np.ndim(Two))
print(Three)
print(np.ndim(Three))

[1 2 3 4 5]
1
[[1 2 3 4 5]
 [1 2 3 4 5]]
2
[[[ 1  2  3  4  4]
  [ 1  2  3  5  4]]

 [[ 1 23  4  4  4]
  [ 1  2  3  4  5]]]
3


List Vs Numpy Array

In [8]:
list=['sa',1,34,44]    # List different datatype
arr=np.array([1,2,3,4,5])  # Array Similar datatype
#all element type will be string    Type conversion if we add string in numpy array

In [ ]:
#Mathematical Operations 
# numpy arra / 5
# List /  5            through error

More Advantages of Numpy Array over list
Array consumes less memory
Array are faster than lists

Array Reshaping
data 1D array
data.reshape(2 row, 3 col)  2D array  ->  3 row 2 col

Array Indexing
data
data[0,1]   row 0 FIrst 1 col
data[1:3]   row from 1 to 3 all cols
data[0:2,0]  first 2 rows from 0   to of 0 colums

In [ ]:
arr=np.array([1,2,3,4,5,6,6,7,7,8,9,10])  # 1 D Array
# 1D array to 2 D array
newarr=arr.reshape(4,3)
print(arr)
print(newarr)
harr=arr.reshape(2,6)
print(harr)
# 3D array
darr=arr.reshape(2,3,2)
print(darr)

[ 1  2  3  4  5  6  6  7  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  7]
 [ 8  9 10]]
[[ 1  2  3  4  5  6]
 [ 6  7  7  8  9 10]]


Array Indexing
Array Indexing is the same as accessing an array element
You can access an array element by referring to its inex number

In [28]:
arr=np.array([1,2,3,4,5,6,6,7,7,8,9,10])
print(arr[2])
print(arr[5])
print(arr[4]+arr[5])
narr=arr.reshape(4,3)
print(narr[2,2])
print(narr[3])
print(narr[0:2])
print(narr[0:4,0:3])

#3 D array
darr=arr.reshape(2,3,2)
print(darr)
print(darr[0,1,1])
print(darr[1,1,0])

3
6
11
7
[ 8  9 10]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  7]
 [ 8  9 10]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 6  7]
  [ 7  8]
  [ 9 10]]]
4
7
